### ISSUE TITLE
TypeError (type 'Null' is not a subtype of type 'Reference')

### ISSUE THREAD

**Issue by 17martix** [mattreid1/firebase_image#40] opened 2021-04-11 18:26 UTC
my app was crashing every time firebase_image was loading picture stating TypeError (type 'Null' is not a subtype of type 'Reference'). after looking into the code, it's the FirebaseImageObject.fromMap(Map<String, dynamic> map) method in image_object.dart causing the error because it's called with no value given to the reference key.

potential solution: make Reference variable in FirebaseImageObject nullable and it solves the problem.

**Comment by Yayo-Arellano** [comment] 2021-04-20 12:59
I also have the same problem

```
======== Exception caught by image resource service ================================================
The following _TypeError was thrown resolving an image codec:
type 'Null' is not a subtype of type 'Reference'

When the exception was thrown, this was the stack: 
#0      new FirebaseImageObject.fromMap (package:firebase_image/src/image_object.dart:32:21)
#1      FirebaseImageCacheManager.get (package:firebase_image/src/cache_manager.dart:93:31)
<asynchronous suspension>
#2      FirebaseImage._fetchImage (package:firebase_image/src/firebase_image.dart:82:11)
<asynchronous suspension>
...
====================================================================================================

```

**Comment by JErazo7** [comment] 2021-04-26 04:33
Any solution?

**Comment by ABleas** [comment] 2021-05-15 10:09
I ran into this as well, after upgrading my project to null safe.

**Comment by difelice** [comment] 2021-05-15 16:21
~Duplicate~
You're right, thanks👇

**Comment by blaugold** [comment] 2021-05-17 09:40
@difelice I don't think this is a duplicate of #37. That issue is about a warning of an unnecessary non-null assertion. This issue is about passing `null` to a non-null parameter at runtime and causing an exception.

**Comment by ABleas** [comment] 2021-05-17 12:26
Agree with the above comment, this is a critical bug. Looks like there is a PR fix already. Would be lovely to have the problem solved :)

**Comment by ABleas** [comment] 2021-05-26 02:23
I'd love to use this package but right now it's not displaying images at all.  Is there a work-around for this issue, other than waiting for the PR to be merged?

**Comment by maeddin** [comment] 2021-06-25 19:22
It still does not work. My solution was to use the fork of #45 . Thanks to @blaugold

**Comment by yelkamel** [comment] 2021-11-04 13:18
I have the same issue and the fork of #45 fixed the issue for me, please merge it :)

**Comment by psimondk** [comment] 2021-11-27 12:57
I can only second @yelkamel as I have the same issue - please merge :)

**Comment by kostodo** [comment] 2021-12-24 18:07
Same issue here.

**Comment by janlektonen** [comment] 2021-12-25 10:12
I face the same issue after updating to version 1.1.0

**Comment by mattreid1** [comment] 2021-12-25 10:26
I was unable to replicate but I'll take a look now

**Comment by mattreid1** [comment] 2021-12-25 11:11
Ok, I merged #45 and released 1.1.1 so :crossed_fingers: that fixed it. As I was unable to replicate the problem, please let me know if it works so I can close the issue. Thanks!

**Comment by mattreid1** [comment] 2021-12-30 13:55
Going to close this issue now but if this is still a problem then feel free to reopen it!

**Closed as completed by mattreid1** 2021-12-30 13:55 UTC

**Comment by yelkamel** [comment] 2022-01-25 14:56
this work for me thank you :) @mattreid1

**Comment by psimondk** [comment] 2022-01-25 15:09
Nice work Matt - a very useful library - thanks for closing this issue
